### ISSUE TITLE
Xcode 9: build error

### ISSUE THREAD

**Issue by dizzzz** [4np/UitzendingGemist#24]
when I wanted to update the app I got the following error:

<img width="1203" alt="object_cpp_and_new_issue_ _4np_uitzendinggemist" src="https://user-images.githubusercontent.com/1700062/30748479-b9213232-9fb0-11e7-94bf-d2dda5f2b311.png">

the git project is clean (no local changes). Any idea how to get the app built again?

(using xcode 9 as pushed this week)

**Comment by 4np** [comment]
Hey Dannes,

Thanks for reporting, I will take a look. Just another heads up, the NPO has developed a new (authenticated) API that we can’t really use (although there _is_ a way to use it, but that will be closed soon if we start using it). In practice this basically means that the API can be considered abandoned. As you may have noticed the tips section is rather empty, which is caused by the same abandonment. The result is that the we're at the mercy of the NPO; whenever they decided to close / pull the old API, the app will stop working. Let's hope they don't anytime soon :)

Cheers, Jeroen

**Comment by sberrevoets** [comment]
The solution here is a `pod update RealmSwift`. After it finishes, build again. The project still emits a bunch of warnings, but it compiles just fine.

@4np No recourse to this probably imminent shutdown? :/

**Comment by tomvanhelderen** [comment]
I hope Jeroen will fix it! Thanx,
Tom

**Comment by 4np** [comment]
Hey guys,

Sorry, I was away for the weekend (the weather was just too nice over here ☀️🍁🍂). Version [1.6.0](https://github.com/4np/UitzendingGemist/releases/tag/1.6.0) is now compatible with Xcode 9 / tvOS 11 :)

There are still a couple of warnings (and the code could use some improvement), but you can ignore all of that :)

@sberrevoets : I have been investigating an alternative a while ago, but the new API uses client tokens as well as https, so it seems like they started to close down unwanted API usage... The good news is I managed to find an API token, the bad news is that they can revoke the token at their pleasing. There is some other weirdness in the new API (sorting, searching, etc) that do not support everything I would _like_ to see, nor does is the new API feature par with the current / old one, but on the other hand it _does_ support pagination which makes the app far more responsive. But, let's see where that goes... I'll give it another stab when I have time :)

**Comment by dizzzz** [comment]
thnx for updating! I'll check asap...
