### ISSUE TITLE
Programs don't play anymore

### ISSUE THREAD

**Issue by FrnklyN** [4np/UitzendingGemist#27]
The live section works but individual programs's don't play when clicking on the play icon.

**Comment by lammertw** [comment]
I have the same problem. I get the following in the log:

```
2017-10-29 19:59:15:945 UitzendingGemist[199:6652] Could not play episode (Optional(NPOKit.NPOError.networkError("An SSL error has occurred and a secure connection to the server cannot be made.")))
```

**Comment by 4np** [comment]
Although it is possible that the streaming server (_odis.omroep.nl_) is just down, I suspect the NPO is finally killing off the legacy APIs and streaming servers. When the NPO launched the 2.0 version of their apps in July this year, they also launched new (authenticated) APIs effectively deprecating the APIs this app relies on. Unfortunately the consequence is that this app will cease to work. Let's hope tomorrow the server is back up again and this is just due to maintenance or something...

**Comment by 4np** [comment]
It's working again, so apparently the NPO servers just experienced downtime... 😀
