### ISSUE TITLE
Scrolling on programmes list crashes the app

### ISSUE THREAD

**Issue by ghost** [4np/UitzendingGemist#30]
Steps on my Apple TV 4 with tvOS 11.2.5:
- Select the main menu "Programma's"
- Choose any character, where the program should start with (for e.g. "D")
- Scroll a few items down the list

Actual result: the application crashes and the apple menu is show

Expected result: display new items each time

**Comment by 4np** [comment]
Hi Sander,

I tried to reproduce the issue but I don't experience a crash. Note though that due to API deprecation this app has reached its end of life, and [TV Gemist](https://github.com/4np/TVGemist) is the app that replaces Uitzending Gemist. This repository will remain online, but it will not get any new updates.
