### ISSUE TITLE
Overhaul ideas

### ISSUE THREAD

**Issue by iAmRenzo** [4np/UitzendingGemist#4]
Hi, you asked me for some ideas for the overhaul off your app. These are just my ideas, too bad I can't code myself...
- Add an option to add shows as favourites. There should be a button on the 'programma' information screen.
- Then you could present new episodes of favourites in the shelf (Apple TV Homescreen) and you could add a row of favourites on the 'uitgelicht' page. Both for quick access to favourite shows.
- Some titles of shows/episodes are to long, maybe they could gently scroll (when selected).
- In the 'programma's' view, there is an alphabet. It should fit in one screen, now you have to scroll to see the last letters. The spacing between the letters can be less to fit them without scrolling.
- The screen for the TV show should, in my opinion, look more like this. You see it everywhere on Apple TV. This is from Infuse. The other episodes are below. There is a play button and the other buttons could be removed (except for a "add to favourite" button).
  ![img_2725](https://cloud.githubusercontent.com/assets/1183790/13547216/9d23e458-e2c9-11e5-8859-3503846d9ec6.jpg)
- A 'watched' indicator for seen episodes would be great!
- For Live TV I would separate NPO1/2/3 and the internet channels. Like this one, this is an other app from someone I now use for live TV. It features a current program. It would be nice to have an extra line that shows the next program. This information is there somewhere as "nu & straks". A progress indicator for the current show would be very welcome :)
  ![img_2724](https://cloud.githubusercontent.com/assets/1183790/13547221/e348acfc-e2c9-11e5-8665-15acd2417a3b.jpg)
- If you got a lot of spare time, you could add a tv guide for NPO 1/2/3... 
- And I was wondering. Does time shift work on live tv?

This are just some ideas that pop up.
(and as I said, I'm not a good programmer, but if I can help testing or something let me know)
(and why are we talking english while we both are -I guess- Dutch? :D )

**Comment by 4np** [comment]
Thanks for the feedback Renzo!

Some comments / remarks:
- Favorites: I am aiming to add favorites / favoriting series and a dedicated 'Favorites' view. Having new shows appear on the shelf sound like an interesting idea, I will see if I can add that in as well
- Uitgelicht view will be removed (quite cluttered) in favor of a dedicated view for 'Tips' and another one for 'Popular'
- 'Programma's' view, will still be there and have a more improved UI. Unfortunately the nature of the tab bar is that it allows scrolling when the tabs do not fit. I will see if I can make it fit better, but this might not get resolved
- TV show view will get an update looking more similar to what you added. However, on the dedicated 'Tips' and 'Popular' pages you will be able to play the TV show immediately without navigating to the TV show view. That might change, but it will probably show a bit more slimmed down version.
- I intend to add a 'Search' view as well
- 'Watched' indicator sounds like a good idea :) I will see if I can include that.
- Live TV / Internet TV: do you use it a lot? Do you think it should be included?
- Time Shift: I am not sure if the ATV player supports it?

Yes, why are we writing English instead of Dutch ;) A habit I guess... GitHub is international, the code is and at work my primary language is English :P

**Comment by iAmRenzo** [comment]
- Favourites, great. That really would enhance the app.
- I like the idea of 'uitgelicht' but I understand your opinion. I though with favourites it is a nice way to browse, find something new or just start a favourite show. An everything in one screen.
- Ok. Again, I am not the programmer, just a heavy use user with an eye for design ;)
- That would be handy. A long press could be added to favourite the show.
- Search will be nice too. With live search results? 
- Cool. I know the XoT / Uitzendinggemist app for Kodi has this. Don't know if that helps.
- I now use it in another app, because there is a "nu" program showing. But while the app is active, it doesn't update :-( I could use it. All seems an other app more logical. But then again, with full features it could be great...
- Now, with the other live tv app, it works. But just once, or just a short period of time. Once a second pause resulted in a switch to live again. I don't know if you can "record" this stream for later playback.

:D

**Comment by 13032016** [comment]
Hi Jeroen,

Thanks for the nice and good working app, only have a question , are you also able to make something like de NLziet app, where we can login in for getting the better streaming quality ?

with regards 

kees

**Comment by 4np** [comment]
Okay, it took a while (been too occupied with work, again started over with the complete rewrite as I found the previous version too slow) but some of the issues above have been addressed in the new complete rewrite:

### The current state of things ([release 0.2.0](https://github.com/4np/UitzendingGemist/releases/tag/0.2.0))
- program and episode screens that are much more informational and conform guidelines
- favouriting programs
- continue watching episodes where you left off
- live tv (NPO 1, 2 and 3 in high quality), themed channels in best quality
- update notification when a newer release is available
- last but certainly not least: fast and snappy, separation of concerns

### Things I aim to add / change
- indicator whether or not an episode was watched (was thinking plex-like orange circle)
- work on the list of programs (perhaps add search?) and tweak the UI

### Things I am investigating
- fetching preview stills from video feeds to make the Live channel view richer

Currently the 'Home' view only shows the 'tips'. I was thinking how I could best fill this screen so any suggestions are helpful. There is a new API for 'trending' shows, in addition to the (older) 'recent' and 'popular'.

Also, while the program view is functional, I am not sure I like it. Any input welcome :)

**Comment by iAmRenzo** [comment]
I had a quick look and I owe you a thank you! I am really happy with your efford because I use this app on a daily basis. Now I can use Live TV (with 'nu & straks') and Gemist in one app.

The tips-screen is quite empty indeed. I like the old suggestions (or what was it called). If you'd had nothing to watch, there was always a tip available.
Working with favorites, you could add those there is there are new episodes. Or have the user add three live-tv channels to it. Or (I don't know if this works) add genre's: like comedy, 'actualiteiten', films, series. Or let the user deside which genre's. That way I can always quick access 'actualiteiten' programms as they come on Gemist. Or, add a row of partly watched episodes.
If you have 3, 4 of 5 of these rows, there is always a thing to watch! :)

The program list, with now letters a-e, h-k, etc is nice. Although I prefferd the single letter option (but squeezed a-z within the screen). Also the text list (instead of icons) seemed quicker. It's seems loading screenshots/icons constantly. And some are really low resolution (and others are absent without a placeholder).

Watched markers are highly appreciated. As is the list of programms (see latter paragraph) and search would be nice too. 
Btw: what's the maximum time you can retreive shows?

I hope you don't take this as critizism. I really like your app and afford. Just giving my opinion.

**Comment by 4np** [comment]
I am definitely not taking this as critizism Renzo, I just want to improve the experience of the app and getting some input is great 👍 Thanks for that!

I think it is a _great_ idea to list new episodes of a show you have favorited on the main / tips screen which would probably make more sense than showing overall recents. As I mentioned earlier the iOS app uses a new trending API which may be interesting to show as well.

I am with you regarding the programs overview page, I was actually taking the A-Z tabs out as I feel it looks better with that tabbar gone. It's true that fetching the images is sometimes a bit wonky and not all programs (or their episodes) do provide a proper image. Often you need to fetch to iterate over a whole chain to find an image you can use (program, episode, get the details of a program, get the details of an episode, check for stills) which can cause quite some delays. So yeah perhaps it should just be a list or programs instead.

Showing the complete alphabet in the tab bar unfortunately does not seem to be possible due to the constraints of the tabbar and its items.

An overview per genre might be good as well, I will look into that :)

Thanks again for you input, you might see a software update notification at some point in the near future ;)

**Comment by 4np** [comment]
@13032016 (Kees): NLZiet is a separate service by the combined effort of the NPO, RTL and SBS which I currently do not aim to cover (if at all). The goal of this app is to provide an as good as possible application to bring Uitzending Gemist to the Apple TV 4.

**Comment by 4np** [comment]
@iAmRenzo what do you think of the new program overview screen in ([release 0.2.1](https://github.com/4np/UitzendingGemist/releases/tag/0.2.1))? I changed it from a tabbed view to a split view so that the letters will now be on the left. I think this UI works a bit better. What do you think?

(ps. I noticed that while _Programma's_ fits in the simulator, it does not on the device so I need to fix that. Maybe it does not even need to be there in the first place.)

![Program Overview](https://cloud.githubusercontent.com/assets/1049693/17215761/468f2b2a-54de-11e6-8afd-ef4bf82fc254.png)

**Comment by iAmRenzo** [comment]
I like it! Just opened a new issue (though this was one closed).

**Comment by 4np** [comment]
And another release. The _tips_ screen now also shows you a list of most recent unwatched episodes for your favourite programs. They are sorted by the number of watched episodes for a program so programs that you frequently watch will be prioritized in the list.

![Tips screen](https://cloud.githubusercontent.com/assets/1049693/17718550/e641069e-6414-11e6-9258-8901ed2d2214.png)

**Comment by 4np** [comment]
And bump to [version 1.0.0](https://github.com/4np/UitzendingGemist/releases/tag/1.0.0) 🙌🏻 Thanks for the ideas! 👍🏻 I am closing down this enhancement request as most of it is covered in the current version. If you have new requests, please open a new enhancement request.
