### ISSUE TITLE
0.2.1 Issues

### ISSUE THREAD

**Issue by iAmRenzo** [4np/UitzendingGemist#6]
I saw version 0.2.1 just before my bug report! So, these are the things I found in the new version.

First of all, it's good to have it in the instructions that you have to use the same bundle id for installing the next version... otherwise a new copy of the app appears. I forgot my previous bundle id and so i lost all the settings... just a minor thing ;)

Programma page: I like this idea! Better than the A-D, E-G thing. I think it's based on the App Store app and the tab of the purchases.
- The word "Programme" is cut off to "Prog...". If you look at the AppStore app, the word is placed where the navigation bar is. It comes in view when you begin to browse.
- The ( and ) around and the different color of the number of episodes for that letter doesn't really add something in my opinion.
- Also, the white bar which highlights the current selection is white... so is the letter of the programs you're seeing. Maybe have a different or translucent bar or change the color of the selected letter. If I look to the AppStore app again, the selection bar is placed behind the text.
- Somehow is the list not smooth to browse. It stutters. I think because it's fetching the data online?
- The title of the show seems a little to far away from the thumbnail.

Live page: nice and clean. I really like "nu" en "straks".
- The digital online channels don't have an icon/thumbnail. It looks a bit weird. You've placed a logo inside for NPO Zapp which is nice. Maybe an idea for the others.
- There is something with the transparency of the icons over the colours. You can see the outline from the logo in a bit different colour while wiggling over the touchpad moving the icons on the screen. Just a minor thing though.

Show page: blends very into the style of Apple TV! Nice.
- However, there is something with the icons. The text is to far away from the button and the icon within the button is a little small. If I compare with Infuse, the measurements are a little off:
  <img width="318" alt="f20c801c-4f1e-11e6-886d-70396c818f81" src="https://cloud.githubusercontent.com/assets/1183790/17241195/57311a32-5570-11e6-9b25-f08ba806eca7.png">
  ![tvshows-show](https://cloud.githubusercontent.com/assets/1183790/17241196/58c44f18-5570-11e6-8d17-81a3b2a2646a.png)
- The icon within the "naar tv programma" doesn't move when the button is pressed.

Furthermore
- I don't know how it all works, and I don't know to policy from NPO. But on the website NPO.nl there are more episode to watch. In the official iOS app there is a limit. And it looks like your app fetches something in the middle. How does that work? Isn't it possible to fetch more episodes of a show?

Well, that's my feedback for today... sorry it's a lot ;)
If I can help in any way, please let me know.

**Comment by 4np** [comment]
Hi Renzo, 

Thanks again for your input 👍 I have just pushed [release 0.3.0](https://github.com/4np/UitzendingGemist/releases/tag/0.3.0) which fixes a number of the issues you reported and it introduces a new 'by day' overview. 

Regarding the latter question, the tvOS app uses the same APIs as the NPO mobile apps so in theory you _should_ see the same information. You web version works differently and does not provide APIs to integrate with, so what is shown there is a completely different implementation. What the tvOS app will show depends on the date the NPO mobile APIs return, which means there are only so many episodes available as the NPO decides to make available :) The new By Day view does allow looking back 17 days instead of _only_ 7 though :)

I will close this issue for now, as most have been solved / addressed. Please open a new ticket if you have more remarks regarding [release 0.3.0](https://github.com/4np/UitzendingGemist/releases/tag/0.3.0)
